// <auto-generated />
#nullable disable
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SistemaContable01.Dashboard.Informes.InformePorTercero
{
    partial class FormInformePorTercero
    {
        private IContainer components = null;

        private Label lblEmpresa;
        private Label lblTitulo;
        private Label lblPeriodo;
        private Label lblGenerado;

        private Label lblTerceroIdent;
        private Label lblTerceroNombre;
        private Label lblTerceroDir;
        private Label lblTerceroCiudadTel;

        private Label lblDesde;
        private Label lblHasta;
        private DateTimePicker dtpDesde;
        private DateTimePicker dtpHasta;

        private Label lblTercero;
        private ComboBox cboTercero;

        private Label lblCuenta;
        private TextBox txtCuenta;

        private Button btnBuscar;
        private Button btnImprimir;

        private DataGridView dgv;

        private Label lblTotDebito;
        private Label lblTotCredito;
        private Label lblSaldoFinal;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components is not null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            lblEmpresa = new Label();
            lblTitulo = new Label();
            lblPeriodo = new Label();
            lblGenerado = new Label();

            lblTerceroIdent = new Label();
            lblTerceroNombre = new Label();
            lblTerceroDir = new Label();
            lblTerceroCiudadTel = new Label();

            lblDesde = new Label();
            lblHasta = new Label();
            dtpDesde = new DateTimePicker();
            dtpHasta = new DateTimePicker();

            lblTercero = new Label();
            cboTercero = new ComboBox();

            lblCuenta = new Label();
            txtCuenta = new TextBox();

            btnBuscar = new Button();
            btnImprimir = new Button();

            dgv = new DataGridView();

            lblTotDebito = new Label();
            lblTotCredito = new Label();
            lblSaldoFinal = new Label();

            ((ISupportInitialize)dgv).BeginInit();
            SuspendLayout();

            // Encabezado
            lblEmpresa.AutoSize = true;
            lblEmpresa.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblEmpresa.Location = new Point(12, 9);
            lblEmpresa.Name = "lblEmpresa";
            lblEmpresa.Size = new Size(74, 20);
            lblEmpresa.Text = "Empresa";

            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTitulo.Location = new Point(12, 31);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(150, 20);
            lblTitulo.Text = "Informe de terceros";

            lblPeriodo.AutoSize = true;
            lblPeriodo.Location = new Point(12, 53);
            lblPeriodo.Name = "lblPeriodo";
            lblPeriodo.Size = new Size(60, 15);
            lblPeriodo.Text = "Período:";

            lblGenerado.AutoSize = true;
            lblGenerado.Location = new Point(12, 70);
            lblGenerado.Name = "lblGenerado";
            lblGenerado.Size = new Size(109, 15);
            lblGenerado.Text = "Generado: (fecha)";

            // Datos tercero
            lblTerceroIdent.AutoSize = true;
            lblTerceroIdent.Location = new Point(12, 95);
            lblTerceroIdent.Name = "lblTerceroIdent";
            lblTerceroIdent.Size = new Size(86, 15);
            lblTerceroIdent.Text = "Identificación:";

            lblTerceroNombre.AutoSize = true;
            lblTerceroNombre.Location = new Point(12, 113);
            lblTerceroNombre.Name = "lblTerceroNombre";
            lblTerceroNombre.Size = new Size(55, 15);
            lblTerceroNombre.Text = "Nombre:";

            lblTerceroDir.AutoSize = true;
            lblTerceroDir.Location = new Point(12, 131);
            lblTerceroDir.Name = "lblTerceroDir";
            lblTerceroDir.Size = new Size(62, 15);
            lblTerceroDir.Text = "Dirección:";

            lblTerceroCiudadTel.AutoSize = true;
            lblTerceroCiudadTel.Location = new Point(12, 149);
            lblTerceroCiudadTel.Name = "lblTerceroCiudadTel";
            lblTerceroCiudadTel.Size = new Size(86, 15);
            lblTerceroCiudadTel.Text = "Ciudad / Tel:";

            // Filtros
            lblDesde.AutoSize = true;
            lblDesde.Location = new Point(420, 15);
            lblDesde.Name = "lblDesde";
            lblDesde.Size = new Size(44, 15);
            lblDesde.Text = "Desde:";

            dtpDesde.Format = DateTimePickerFormat.Short;
            dtpDesde.Location = new Point(470, 11);
            dtpDesde.Name = "dtpDesde";
            dtpDesde.Size = new Size(110, 23);

            lblHasta.AutoSize = true;
            lblHasta.Location = new Point(590, 15);
            lblHasta.Name = "lblHasta";
            lblHasta.Size = new Size(41, 15);
            lblHasta.Text = "Hasta:";

            dtpHasta.Format = DateTimePickerFormat.Short;
            dtpHasta.Location = new Point(640, 11);
            dtpHasta.Name = "dtpHasta";
            dtpHasta.Size = new Size(110, 23);

            lblTercero.AutoSize = true;
            lblTercero.Location = new Point(420, 45);
            lblTercero.Name = "lblTercero";
            lblTercero.Size = new Size(52, 15);
            lblTercero.Text = "Tercero:";

            cboTercero.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTercero.Location = new Point(470, 41);
            cboTercero.Name = "cboTercero";
            cboTercero.Size = new Size(280, 23);

            lblCuenta.AutoSize = true;
            lblCuenta.Location = new Point(420, 75);
            lblCuenta.Name = "lblCuenta";
            lblCuenta.Size = new Size(48, 15);
            lblCuenta.Text = "Cuenta:";

            txtCuenta.Location = new Point(470, 71);
            txtCuenta.Name = "txtCuenta";
            txtCuenta.Size = new Size(120, 23);
            txtCuenta.PlaceholderText = "Opcional";

            btnBuscar.Location = new Point(610, 70);
            btnBuscar.Name = "btnBuscar";
            btnBuscar.Size = new Size(70, 24);
            btnBuscar.Text = "Buscar";
            btnBuscar.UseVisualStyleBackColor = true;
            btnBuscar.Click += btnBuscar_Click;

            btnImprimir.Location = new Point(690, 70);
            btnImprimir.Name = "btnImprimir";
            btnImprimir.Size = new Size(80, 24);
            btnImprimir.Text = "Imprimir";
            btnImprimir.UseVisualStyleBackColor = true;
            btnImprimir.Click += btnImprimir_Click;

            // Grid
            dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgv.Location = new Point(12, 180);
            dgv.Name = "dgv";
            dgv.ReadOnly = true;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.RowHeadersVisible = false;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.Size = new Size(760, 320);

            // Totales
            lblTotDebito.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblTotDebito.AutoSize = true;
            lblTotDebito.Location = new Point(12, 510);
            lblTotDebito.Name = "lblTotDebito";
            lblTotDebito.Size = new Size(70, 15);
            lblTotDebito.Text = "Débito: 0,00";

            lblTotCredito.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblTotCredito.AutoSize = true;
            lblTotCredito.Location = new Point(180, 510);
            lblTotCredito.Name = "lblTotCredito";
            lblTotCredito.Size = new Size(76, 15);
            lblTotCredito.Text = "Crédito: 0,00";

            lblSaldoFinal.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            lblSaldoFinal.AutoSize = true;
            lblSaldoFinal.Location = new Point(360, 510);
            lblSaldoFinal.Name = "lblSaldoFinal";
            lblSaldoFinal.Size = new Size(100, 15);
            lblSaldoFinal.Text = "Saldo final: 0,00";

            // Form
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(784, 541);
            Controls.Add(lblEmpresa);
            Controls.Add(lblTitulo);
            Controls.Add(lblPeriodo);
            Controls.Add(lblGenerado);

            Controls.Add(lblTerceroIdent);
            Controls.Add(lblTerceroNombre);
            Controls.Add(lblTerceroDir);
            Controls.Add(lblTerceroCiudadTel);

            Controls.Add(lblDesde);
            Controls.Add(dtpDesde);
            Controls.Add(lblHasta);
            Controls.Add(dtpHasta);

            Controls.Add(lblTercero);
            Controls.Add(cboTercero);

            Controls.Add(lblCuenta);
            Controls.Add(txtCuenta);

            Controls.Add(btnBuscar);
            Controls.Add(btnImprimir);

            Controls.Add(dgv);

            Controls.Add(lblTotDebito);
            Controls.Add(lblTotCredito);
            Controls.Add(lblSaldoFinal);

            Name = "FormInformePorTercero";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Informe por tercero";
            ((ISupportInitialize)dgv).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}