// <auto-generated />
#nullable disable
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SistemaContable01.Dashboard.PlanCuentas.CrudPlanCuentas
{
    partial class FormCrudPlanCuentas
    {
        private IContainer components = null;

        // Controls (one declaration each)
        private DataGridView dataGridView1;
        private TextBox txtCodigo;
        private TextBox txtNombre;
        private NumericUpDown nudNivel;
        private ComboBox cboNaturaleza;
        private Label lblCodigo;
        private Label lblNombre;
        private Label lblNivel;
        private Label lblNaturaleza;
        private Button btnAgregar;
        private Button btnActualizar;
        private Button btnEliminar;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components is not null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            dataGridView1 = new DataGridView();
            txtCodigo = new TextBox();
            txtNombre = new TextBox();
            nudNivel = new NumericUpDown();
            cboNaturaleza = new ComboBox();
            lblCodigo = new Label();
            lblNombre = new Label();
            lblNivel = new Label();
            lblNaturaleza = new Label();
            btnAgregar = new Button();
            btnActualizar = new Button();
            btnEliminar = new Button();
            ((ISupportInitialize)dataGridView1).BeginInit();
            ((ISupportInitialize)nudNivel).BeginInit();
            SuspendLayout();
            // 
            // dataGridView1
            // 
            dataGridView1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dataGridView1.Location = new Point(12, 120);
            dataGridView1.Name = "dataGridView1";
            dataGridView1.ReadOnly = true;
            dataGridView1.RowHeadersVisible = false;
            dataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dataGridView1.MultiSelect = false;
            dataGridView1.AllowUserToAddRows = false;
            dataGridView1.AllowUserToDeleteRows = false;
            dataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dataGridView1.Size = new Size(776, 318);
            dataGridView1.TabIndex = 10;
            dataGridView1.SelectionChanged += dataGridView1_SelectionChanged;
            // 
            // lblCodigo
            // 
            lblCodigo.AutoSize = true;
            lblCodigo.Location = new Point(12, 15);
            lblCodigo.Name = "lblCodigo";
            lblCodigo.Size = new Size(54, 15);
            lblCodigo.Text = "Código:";
            // 
            // txtCodigo
            // 
            txtCodigo.Location = new Point(90, 12);
            txtCodigo.Name = "txtCodigo";
            txtCodigo.Size = new Size(120, 23);
            txtCodigo.TabIndex = 0;
            // 
            // lblNombre
            // 
            lblNombre.AutoSize = true;
            lblNombre.Location = new Point(220, 15);
            lblNombre.Name = "lblNombre";
            lblNombre.Size = new Size(58, 15);
            lblNombre.Text = "Nombre:";
            // 
            // txtNombre
            // 
            txtNombre.Location = new Point(284, 12);
            txtNombre.Name = "txtNombre";
            txtNombre.Size = new Size(250, 23);
            txtNombre.TabIndex = 1;
            // 
            // lblNivel
            // 
            lblNivel.AutoSize = true;
            lblNivel.Location = new Point(12, 54);
            lblNivel.Name = "lblNivel";
            lblNivel.Size = new Size(38, 15);
            lblNivel.Text = "Nivel:";
            // 
            // nudNivel
            // 
            nudNivel.Location = new Point(90, 50);
            nudNivel.Minimum = 0;
            nudNivel.Maximum = 10;
            nudNivel.Name = "nudNivel";
            nudNivel.Size = new Size(120, 23);
            nudNivel.TabIndex = 2;
            // 
            // lblNaturaleza
            // 
            lblNaturaleza.AutoSize = true;
            lblNaturaleza.Location = new Point(220, 54);
            lblNaturaleza.Name = "lblNaturaleza";
            lblNaturaleza.Size = new Size(71, 15);
            lblNaturaleza.Text = "Naturaleza:";
            // 
            // cboNaturaleza
            // 
            cboNaturaleza.DropDownStyle = ComboBoxStyle.DropDownList;
            cboNaturaleza.Items.AddRange(new object[] { "", "DEBITO", "CREDITO" });
            cboNaturaleza.Location = new Point(298, 50);
            cboNaturaleza.Name = "cboNaturaleza";
            cboNaturaleza.Size = new Size(150, 23);
            cboNaturaleza.TabIndex = 3;
            // 
            // btnAgregar
            // 
            btnAgregar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnAgregar.Location = new Point(488, 12);
            btnAgregar.Name = "btnAgregar";
            btnAgregar.Size = new Size(90, 61);
            btnAgregar.TabIndex = 4;
            btnAgregar.Text = "Agregar";
            btnAgregar.UseVisualStyleBackColor = true;
            btnAgregar.Click += btnAgregar_Click;
            // 
            // btnActualizar
            // 
            btnActualizar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnActualizar.Location = new Point(584, 12);
            btnActualizar.Name = "btnActualizar";
            btnActualizar.Size = new Size(90, 61);
            btnActualizar.TabIndex = 5;
            btnActualizar.Text = "Actualizar";
            btnActualizar.UseVisualStyleBackColor = true;
            btnActualizar.Click += btnActualizar_Click;
            // 
            // btnEliminar
            // 
            btnEliminar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnEliminar.Location = new Point(680, 12);
            btnEliminar.Name = "btnEliminar";
            btnEliminar.Size = new Size(108, 61);
            btnEliminar.TabIndex = 6;
            btnEliminar.Text = "Eliminar";
            btnEliminar.UseVisualStyleBackColor = true;
            btnEliminar.Click += btnEliminar_Click;
            // 
            // CrudPlanCuentas
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(800, 450);
            Controls.Add(btnEliminar);
            Controls.Add(btnActualizar);
            Controls.Add(btnAgregar);
            Controls.Add(cboNaturaleza);
            Controls.Add(lblNaturaleza);
            Controls.Add(nudNivel);
            Controls.Add(lblNivel);
            Controls.Add(txtNombre);
            Controls.Add(lblNombre);
            Controls.Add(txtCodigo);
            Controls.Add(lblCodigo);
            Controls.Add(dataGridView1);
            Name = "CrudPlanCuentas";
            StartPosition = FormStartPosition.CenterParent;
            Text = "CRUD - Plan de Cuentas (PUC)";
            ((ISupportInitialize)dataGridView1).EndInit();
            ((ISupportInitialize)nudNivel).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }
    }
}